service: 
  name: demo-nodejs-event-driven-serverless

custom:
  serverless-offline:
    port: 3000

provider:
  name: aws
  runtime: nodejs8.10

functions:

  event:
    handler: src/handler.createEvent
    events:
      - http:
          path: create-event
          method: get        

plugins:
  - serverless-offline
